.TH mllex 1 "February 6, 2018"
.SH NAME
\fBmllex\fP \- lexer generator for use with Standard ML and MLton
.SH SYNOPSIS
\fBmllex foo.lex\fR
.SH DESCRIPTION
.PP
\fBmllex\fP takes as input a lexer specification \fBfoo.lex\fP and produces as
output in \fBfoo.lex.sml\fP a lexer written in SML.

For details on the lexer specification, see \fBA Lexical Analyzer Generator for
Standard ML\fP, which is in \fB/usr/share/doc/mlton/mllex.pdf\fP.

.SH "SEE ALSO"

.BR mlton (1), mlyacc (1)
