.TH mlnlffigen 1 "February 6, 2018"
.SH NAME
\fBmlnlffigen\fP \- glue-code generator for use with the new "NLFFI" foreign function interface for Standard ML and MLton
.SH SYNOPSIS
\fBmlnlffigen [option ...] C-file ...\fR
.SH DESCRIPTION
.PP
\fBmlnlffigen\fP takes as input a C source file and produces as output in \fBNLFFI-Generated\fP 
the glue-code for Standard ML and in \fBNLFFI-Generated\\nlffi-generated.mlb\fP a ML Basis system file.

.SH "SEE ALSO"

.BR mlton (1)
