.TH mlprof 1 "January 13, 2003"
.SH NAME
\fBmlprof\fP \- display profiling information from MLton-compiled executable
.SH SYNOPSIS
\fBmlprof \fI[option ...] a.out mlmon.out [mlmon.out ...]\fR
.SH DESCRIPTION
.PP
\fBmlprof\fP extracts information from an executable compiled by
\fBMLton\fP with \fB-profile alloc\fP or \fB-profile time\fP option
and the resulting \fBmlmon.out\fP file produced by running the
executable.

The output of \fBmlprof\fP consists of an initial line indicating the
total amount of CPU time or bytes allocated.  After this, source
functions are listed along with the percentage of this total that they
used, in decreasing order.  If the program was compiled with
\fB-profile-stack true\fP, \fBmlprof\fP will display the time spent or
bytes allocated while the function was on the stack and in GC in
addition to the time or bytes that the function is responsible for.

\fBmlprof\fP writes a call graph containing the table data to a file
with the executable name and suffix \fB.dot\fP.

With multiple \fBmlmon.out\fP files, \fBmlprof\fP will sum the
profiling information.

.SH OPTIONS
.TP
\fB-graph \fI{\fBexp\fP}\fP
Show nodes in the call graph specified by \fBexp\fP.  For details on
the allowed expressions, see the \fBMLton User Guide\fP.
.TP
\fB-graph-title \fI{\fBstring\fP}\fP
Set the call-graph title.
.TP
\fB-mlmon \fI{\fBfile\fP}\fP
Process the list of whitespace-separated mlmon.out files found in the
specified file.
.TP
\fB-raw \fI{\fBfalse\fP|\fBtrue\fP}\fP
Show the raw counts in addition to the percentages.
.TP
\fB-show-line \fI{\fBfalse\fP|\fBtrue\fP}\fP
Show the file and line for each function.
.TP
\fB-thresh \fI{\fBx\fP}\fP
Only print information about functions whose percentage is above
\fBx\fP, where 0 <= \fBx\fP <= 100.0.
.SH "SEE ALSO"
.BR mlton (1)
