.TH mlyacc 1 "February 6, 2018"
.SH NAME
\fBmlyacc\fP \- parser generator for use with Standard ML and MLton
.SH SYNOPSIS
\fBmlyacc foo.grm\fR
.SH DESCRIPTION
.PP
\fBmlyacc\fP takes as input a parser specification \fBfoo.grm\fP and produces as
output in \fBfoo.grm.sig\fP and \fBfoo.grm.sml\fP a parser written in SML.

For details on the parser specification, see the \fBML-Yacc User's Manual\fP,
which is in \fB/usr/share/doc/mlton/mlyacc.pdf\fP.

.SH "SEE ALSO"

.BR mllex (1), mlton (1)
