Bugs20130715
============

Here are the known bugs in <:Release20130715:MLton 20130715>, listed
in reverse chronological order of date reported.

* <!Anchor(bug06)>
Bug with simultaneous `sharing` of multiple structures.
+
Fixed by commit <!ViewGitCommit(mlton,9cb5164f6)>.

* <!Anchor(bug05)>
Minor bug with exception replication.
+
Fixed by commit <!ViewGitCommit(mlton,1c89c42f6)>.

* <!Anchor(bug04)>
Minor bug erroneously accepting symbolic identifiers for strid, sigid, and fctid
and erroneously accepting symbolic identifiers before `.` in long identifiers.
+
Fixed by commit <!ViewGitCommit(mlton,9a56be647)>.

* <!Anchor(bug03)>
Minor bug in precedence parsing of function clauses.
+
Fixed by commit <!ViewGitCommit(mlton,1a6d25ec9)>.

* <!Anchor(bug02)>
Performance bug in creation of worker threads to service calls of `_export`-ed
functions.
+
Thanks to Bernard Berthomieu for the bug report.
+
Fixed by commit <!ViewGitCommit(mlton,97c2bdf1d)>.

* <!Anchor(bug01)>
Bug in `MLton.IntInf.fromRep` that could yield values that violate the `IntInf`
representation invariants.
+
Thanks to Rob Simmons for the bug report.
+
Fixed by commit <!ViewGitCommit(mlton,3add91eda)>.

* <!Anchor(bug00)>
Bug in equality status of some arrays, vectors, and slices in Basis Library
implementation.
+
Fixed by commit <!ViewGitCommit(mlton,a7ed9cbf1)>.
