MLton
=====

MLton is a whole-program optimizing compiler for the Standard{nbsp}ML
programming language.  MLton generates small executables with
excellent runtime performance, utilizing untagged and unboxed native
integers, reals, and words, unboxed native arrays, fast
arbitrary-precision arithmetic based on GMP, and multiple code
generation and garbage collection strategies.  In addition, MLton
provides a feature rich Standard{nbsp}ML programming environment, with
full support for SML97 as given in The Definition of Standard{nbsp}ML
(Revised), a number of useful language extensions, a complete
implementation of the Standard ML Basis Library, various useful
libraries, a simple and fast C foreign function interface, the ML
Basis system for programming with source libraries, and tools such as
a lexer generator, a parser generator, and a profiler.

== What's new? ==

* 20200722: Please try out our latest release, <:Release20200722:MLton 20200722>.

* 20180207: Please try out our latest release, <:Release20180207:MLton 20180207>.

* 20140730: http://www.cs.rit.edu/%7emtf[Matthew Fluet] and
  http://www.cse.buffalo.edu/%7elziarek[Lukasz Ziarek] have been
  awarded an http://www.nsf.gov/funding/pgm_summ.jsp?pims_id=12810[NSF
  CISE Research Infrastructure (CRI)] grant titled "Positioning MLton
  for Next-Generation Programming Languages Research;" read the award
  abstracts
  (http://www.nsf.gov/awardsearch/showAward?AWD_ID=1405770[Award{nbsp}#1405770]
  and
  http://www.nsf.gov/awardsearch/showAward?AWD_ID=1405614[Award{nbsp}#1405614])
  for more details.

== Next steps ==

* Visit the https://github.com/MLton/mlton[MLton GitHub repository].
* Read about MLton's <:Features:>.
* Look at <:Documentation:>.
* See some <:Users:> of MLton.
* Download MLton from https://sourceforge.net/projects/mlton/files/mlton/20200722[SourceForge] or https://github.com/MLton/mlton/releases/tag/on-20200722-release[GitHub].
* Meet the MLton <:Developers:>.
* Get involved with MLton <:Development:>.
* User-maintained <:FAQ:>.
* <:Contact:> us.
