(* This file is automatically generated.  Do not edit. *)
fun f (x: Int.int) = ~ x
fun f (x: IntInf.int) = ~ x
fun f (x: LargeInt.int) = ~ x
fun f (x: FixedInt.int) = ~ x
fun f (x: Position.int) = ~ x
fun f (x: Int2.int) = ~ x
fun f (x: Int3.int) = ~ x
fun f (x: Int4.int) = ~ x
fun f (x: Int5.int) = ~ x
fun f (x: Int6.int) = ~ x
fun f (x: Int7.int) = ~ x
fun f (x: Int8.int) = ~ x
fun f (x: Int9.int) = ~ x
fun f (x: Int10.int) = ~ x
fun f (x: Int11.int) = ~ x
fun f (x: Int12.int) = ~ x
fun f (x: Int13.int) = ~ x
fun f (x: Int14.int) = ~ x
fun f (x: Int15.int) = ~ x
fun f (x: Int16.int) = ~ x
fun f (x: Int17.int) = ~ x
fun f (x: Int18.int) = ~ x
fun f (x: Int19.int) = ~ x
fun f (x: Int20.int) = ~ x
fun f (x: Int21.int) = ~ x
fun f (x: Int22.int) = ~ x
fun f (x: Int23.int) = ~ x
fun f (x: Int24.int) = ~ x
fun f (x: Int25.int) = ~ x
fun f (x: Int26.int) = ~ x
fun f (x: Int27.int) = ~ x
fun f (x: Int28.int) = ~ x
fun f (x: Int29.int) = ~ x
fun f (x: Int30.int) = ~ x
fun f (x: Int31.int) = ~ x
fun f (x: Int32.int) = ~ x
fun f (x: Int64.int) = ~ x
fun f (x: Word.word) = ~ x
fun f (x: LargeWord.word) = ~ x
fun f (x: SysWord.word) = ~ x
fun f (x: Word2.word) = ~ x
fun f (x: Word3.word) = ~ x
fun f (x: Word4.word) = ~ x
fun f (x: Word5.word) = ~ x
fun f (x: Word6.word) = ~ x
fun f (x: Word7.word) = ~ x
fun f (x: Word8.word) = ~ x
fun f (x: Word9.word) = ~ x
fun f (x: Word10.word) = ~ x
fun f (x: Word11.word) = ~ x
fun f (x: Word12.word) = ~ x
fun f (x: Word13.word) = ~ x
fun f (x: Word14.word) = ~ x
fun f (x: Word15.word) = ~ x
fun f (x: Word16.word) = ~ x
fun f (x: Word17.word) = ~ x
fun f (x: Word18.word) = ~ x
fun f (x: Word19.word) = ~ x
fun f (x: Word20.word) = ~ x
fun f (x: Word21.word) = ~ x
fun f (x: Word22.word) = ~ x
fun f (x: Word23.word) = ~ x
fun f (x: Word24.word) = ~ x
fun f (x: Word25.word) = ~ x
fun f (x: Word26.word) = ~ x
fun f (x: Word27.word) = ~ x
fun f (x: Word28.word) = ~ x
fun f (x: Word29.word) = ~ x
fun f (x: Word30.word) = ~ x
fun f (x: Word31.word) = ~ x
fun f (x: Word32.word) = ~ x
fun f (x: Word64.word) = ~ x
fun f (x: Real.real) = ~ x
fun f (x: Real32.real) = ~ x
fun f (x: Real64.real) = ~ x
fun f (x: LargeReal.real) = ~ x
fun f (x: Int.int) = x + x
fun f (x: IntInf.int) = x + x
fun f (x: LargeInt.int) = x + x
fun f (x: FixedInt.int) = x + x
fun f (x: Position.int) = x + x
fun f (x: Int2.int) = x + x
fun f (x: Int3.int) = x + x
fun f (x: Int4.int) = x + x
fun f (x: Int5.int) = x + x
fun f (x: Int6.int) = x + x
fun f (x: Int7.int) = x + x
fun f (x: Int8.int) = x + x
fun f (x: Int9.int) = x + x
fun f (x: Int10.int) = x + x
fun f (x: Int11.int) = x + x
fun f (x: Int12.int) = x + x
fun f (x: Int13.int) = x + x
fun f (x: Int14.int) = x + x
fun f (x: Int15.int) = x + x
fun f (x: Int16.int) = x + x
fun f (x: Int17.int) = x + x
fun f (x: Int18.int) = x + x
fun f (x: Int19.int) = x + x
fun f (x: Int20.int) = x + x
fun f (x: Int21.int) = x + x
fun f (x: Int22.int) = x + x
fun f (x: Int23.int) = x + x
fun f (x: Int24.int) = x + x
fun f (x: Int25.int) = x + x
fun f (x: Int26.int) = x + x
fun f (x: Int27.int) = x + x
fun f (x: Int28.int) = x + x
fun f (x: Int29.int) = x + x
fun f (x: Int30.int) = x + x
fun f (x: Int31.int) = x + x
fun f (x: Int32.int) = x + x
fun f (x: Int64.int) = x + x
fun f (x: Word.word) = x + x
fun f (x: LargeWord.word) = x + x
fun f (x: SysWord.word) = x + x
fun f (x: Word2.word) = x + x
fun f (x: Word3.word) = x + x
fun f (x: Word4.word) = x + x
fun f (x: Word5.word) = x + x
fun f (x: Word6.word) = x + x
fun f (x: Word7.word) = x + x
fun f (x: Word8.word) = x + x
fun f (x: Word9.word) = x + x
fun f (x: Word10.word) = x + x
fun f (x: Word11.word) = x + x
fun f (x: Word12.word) = x + x
fun f (x: Word13.word) = x + x
fun f (x: Word14.word) = x + x
fun f (x: Word15.word) = x + x
fun f (x: Word16.word) = x + x
fun f (x: Word17.word) = x + x
fun f (x: Word18.word) = x + x
fun f (x: Word19.word) = x + x
fun f (x: Word20.word) = x + x
fun f (x: Word21.word) = x + x
fun f (x: Word22.word) = x + x
fun f (x: Word23.word) = x + x
fun f (x: Word24.word) = x + x
fun f (x: Word25.word) = x + x
fun f (x: Word26.word) = x + x
fun f (x: Word27.word) = x + x
fun f (x: Word28.word) = x + x
fun f (x: Word29.word) = x + x
fun f (x: Word30.word) = x + x
fun f (x: Word31.word) = x + x
fun f (x: Word32.word) = x + x
fun f (x: Word64.word) = x + x
fun f (x: Real.real) = x + x
fun f (x: Real32.real) = x + x
fun f (x: Real64.real) = x + x
fun f (x: LargeReal.real) = x + x
fun f (x: Int.int) = x - x
fun f (x: IntInf.int) = x - x
fun f (x: LargeInt.int) = x - x
fun f (x: FixedInt.int) = x - x
fun f (x: Position.int) = x - x
fun f (x: Int2.int) = x - x
fun f (x: Int3.int) = x - x
fun f (x: Int4.int) = x - x
fun f (x: Int5.int) = x - x
fun f (x: Int6.int) = x - x
fun f (x: Int7.int) = x - x
fun f (x: Int8.int) = x - x
fun f (x: Int9.int) = x - x
fun f (x: Int10.int) = x - x
fun f (x: Int11.int) = x - x
fun f (x: Int12.int) = x - x
fun f (x: Int13.int) = x - x
fun f (x: Int14.int) = x - x
fun f (x: Int15.int) = x - x
fun f (x: Int16.int) = x - x
fun f (x: Int17.int) = x - x
fun f (x: Int18.int) = x - x
fun f (x: Int19.int) = x - x
fun f (x: Int20.int) = x - x
fun f (x: Int21.int) = x - x
fun f (x: Int22.int) = x - x
fun f (x: Int23.int) = x - x
fun f (x: Int24.int) = x - x
fun f (x: Int25.int) = x - x
fun f (x: Int26.int) = x - x
fun f (x: Int27.int) = x - x
fun f (x: Int28.int) = x - x
fun f (x: Int29.int) = x - x
fun f (x: Int30.int) = x - x
fun f (x: Int31.int) = x - x
fun f (x: Int32.int) = x - x
fun f (x: Int64.int) = x - x
fun f (x: Word.word) = x - x
fun f (x: LargeWord.word) = x - x
fun f (x: SysWord.word) = x - x
fun f (x: Word2.word) = x - x
fun f (x: Word3.word) = x - x
fun f (x: Word4.word) = x - x
fun f (x: Word5.word) = x - x
fun f (x: Word6.word) = x - x
fun f (x: Word7.word) = x - x
fun f (x: Word8.word) = x - x
fun f (x: Word9.word) = x - x
fun f (x: Word10.word) = x - x
fun f (x: Word11.word) = x - x
fun f (x: Word12.word) = x - x
fun f (x: Word13.word) = x - x
fun f (x: Word14.word) = x - x
fun f (x: Word15.word) = x - x
fun f (x: Word16.word) = x - x
fun f (x: Word17.word) = x - x
fun f (x: Word18.word) = x - x
fun f (x: Word19.word) = x - x
fun f (x: Word20.word) = x - x
fun f (x: Word21.word) = x - x
fun f (x: Word22.word) = x - x
fun f (x: Word23.word) = x - x
fun f (x: Word24.word) = x - x
fun f (x: Word25.word) = x - x
fun f (x: Word26.word) = x - x
fun f (x: Word27.word) = x - x
fun f (x: Word28.word) = x - x
fun f (x: Word29.word) = x - x
fun f (x: Word30.word) = x - x
fun f (x: Word31.word) = x - x
fun f (x: Word32.word) = x - x
fun f (x: Word64.word) = x - x
fun f (x: Real.real) = x - x
fun f (x: Real32.real) = x - x
fun f (x: Real64.real) = x - x
fun f (x: LargeReal.real) = x - x
fun f (x: Int.int) = x * x
fun f (x: IntInf.int) = x * x
fun f (x: LargeInt.int) = x * x
fun f (x: FixedInt.int) = x * x
fun f (x: Position.int) = x * x
fun f (x: Int2.int) = x * x
fun f (x: Int3.int) = x * x
fun f (x: Int4.int) = x * x
fun f (x: Int5.int) = x * x
fun f (x: Int6.int) = x * x
fun f (x: Int7.int) = x * x
fun f (x: Int8.int) = x * x
fun f (x: Int9.int) = x * x
fun f (x: Int10.int) = x * x
fun f (x: Int11.int) = x * x
fun f (x: Int12.int) = x * x
fun f (x: Int13.int) = x * x
fun f (x: Int14.int) = x * x
fun f (x: Int15.int) = x * x
fun f (x: Int16.int) = x * x
fun f (x: Int17.int) = x * x
fun f (x: Int18.int) = x * x
fun f (x: Int19.int) = x * x
fun f (x: Int20.int) = x * x
fun f (x: Int21.int) = x * x
fun f (x: Int22.int) = x * x
fun f (x: Int23.int) = x * x
fun f (x: Int24.int) = x * x
fun f (x: Int25.int) = x * x
fun f (x: Int26.int) = x * x
fun f (x: Int27.int) = x * x
fun f (x: Int28.int) = x * x
fun f (x: Int29.int) = x * x
fun f (x: Int30.int) = x * x
fun f (x: Int31.int) = x * x
fun f (x: Int32.int) = x * x
fun f (x: Int64.int) = x * x
fun f (x: Word.word) = x * x
fun f (x: LargeWord.word) = x * x
fun f (x: SysWord.word) = x * x
fun f (x: Word2.word) = x * x
fun f (x: Word3.word) = x * x
fun f (x: Word4.word) = x * x
fun f (x: Word5.word) = x * x
fun f (x: Word6.word) = x * x
fun f (x: Word7.word) = x * x
fun f (x: Word8.word) = x * x
fun f (x: Word9.word) = x * x
fun f (x: Word10.word) = x * x
fun f (x: Word11.word) = x * x
fun f (x: Word12.word) = x * x
fun f (x: Word13.word) = x * x
fun f (x: Word14.word) = x * x
fun f (x: Word15.word) = x * x
fun f (x: Word16.word) = x * x
fun f (x: Word17.word) = x * x
fun f (x: Word18.word) = x * x
fun f (x: Word19.word) = x * x
fun f (x: Word20.word) = x * x
fun f (x: Word21.word) = x * x
fun f (x: Word22.word) = x * x
fun f (x: Word23.word) = x * x
fun f (x: Word24.word) = x * x
fun f (x: Word25.word) = x * x
fun f (x: Word26.word) = x * x
fun f (x: Word27.word) = x * x
fun f (x: Word28.word) = x * x
fun f (x: Word29.word) = x * x
fun f (x: Word30.word) = x * x
fun f (x: Word31.word) = x * x
fun f (x: Word32.word) = x * x
fun f (x: Word64.word) = x * x
fun f (x: Real.real) = x * x
fun f (x: Real32.real) = x * x
fun f (x: Real64.real) = x * x
fun f (x: LargeReal.real) = x * x
fun f (x: Real.real) = x / x
fun f (x: Real32.real) = x / x
fun f (x: Real64.real) = x / x
fun f (x: LargeReal.real) = x / x
fun f (x: Int.int) = x div x
fun f (x: IntInf.int) = x div x
fun f (x: LargeInt.int) = x div x
fun f (x: FixedInt.int) = x div x
fun f (x: Position.int) = x div x
fun f (x: Int2.int) = x div x
fun f (x: Int3.int) = x div x
fun f (x: Int4.int) = x div x
fun f (x: Int5.int) = x div x
fun f (x: Int6.int) = x div x
fun f (x: Int7.int) = x div x
fun f (x: Int8.int) = x div x
fun f (x: Int9.int) = x div x
fun f (x: Int10.int) = x div x
fun f (x: Int11.int) = x div x
fun f (x: Int12.int) = x div x
fun f (x: Int13.int) = x div x
fun f (x: Int14.int) = x div x
fun f (x: Int15.int) = x div x
fun f (x: Int16.int) = x div x
fun f (x: Int17.int) = x div x
fun f (x: Int18.int) = x div x
fun f (x: Int19.int) = x div x
fun f (x: Int20.int) = x div x
fun f (x: Int21.int) = x div x
fun f (x: Int22.int) = x div x
fun f (x: Int23.int) = x div x
fun f (x: Int24.int) = x div x
fun f (x: Int25.int) = x div x
fun f (x: Int26.int) = x div x
fun f (x: Int27.int) = x div x
fun f (x: Int28.int) = x div x
fun f (x: Int29.int) = x div x
fun f (x: Int30.int) = x div x
fun f (x: Int31.int) = x div x
fun f (x: Int32.int) = x div x
fun f (x: Int64.int) = x div x
fun f (x: Word.word) = x div x
fun f (x: LargeWord.word) = x div x
fun f (x: SysWord.word) = x div x
fun f (x: Word2.word) = x div x
fun f (x: Word3.word) = x div x
fun f (x: Word4.word) = x div x
fun f (x: Word5.word) = x div x
fun f (x: Word6.word) = x div x
fun f (x: Word7.word) = x div x
fun f (x: Word8.word) = x div x
fun f (x: Word9.word) = x div x
fun f (x: Word10.word) = x div x
fun f (x: Word11.word) = x div x
fun f (x: Word12.word) = x div x
fun f (x: Word13.word) = x div x
fun f (x: Word14.word) = x div x
fun f (x: Word15.word) = x div x
fun f (x: Word16.word) = x div x
fun f (x: Word17.word) = x div x
fun f (x: Word18.word) = x div x
fun f (x: Word19.word) = x div x
fun f (x: Word20.word) = x div x
fun f (x: Word21.word) = x div x
fun f (x: Word22.word) = x div x
fun f (x: Word23.word) = x div x
fun f (x: Word24.word) = x div x
fun f (x: Word25.word) = x div x
fun f (x: Word26.word) = x div x
fun f (x: Word27.word) = x div x
fun f (x: Word28.word) = x div x
fun f (x: Word29.word) = x div x
fun f (x: Word30.word) = x div x
fun f (x: Word31.word) = x div x
fun f (x: Word32.word) = x div x
fun f (x: Word64.word) = x div x
fun f (x: Int.int) = x mod x
fun f (x: IntInf.int) = x mod x
fun f (x: LargeInt.int) = x mod x
fun f (x: FixedInt.int) = x mod x
fun f (x: Position.int) = x mod x
fun f (x: Int2.int) = x mod x
fun f (x: Int3.int) = x mod x
fun f (x: Int4.int) = x mod x
fun f (x: Int5.int) = x mod x
fun f (x: Int6.int) = x mod x
fun f (x: Int7.int) = x mod x
fun f (x: Int8.int) = x mod x
fun f (x: Int9.int) = x mod x
fun f (x: Int10.int) = x mod x
fun f (x: Int11.int) = x mod x
fun f (x: Int12.int) = x mod x
fun f (x: Int13.int) = x mod x
fun f (x: Int14.int) = x mod x
fun f (x: Int15.int) = x mod x
fun f (x: Int16.int) = x mod x
fun f (x: Int17.int) = x mod x
fun f (x: Int18.int) = x mod x
fun f (x: Int19.int) = x mod x
fun f (x: Int20.int) = x mod x
fun f (x: Int21.int) = x mod x
fun f (x: Int22.int) = x mod x
fun f (x: Int23.int) = x mod x
fun f (x: Int24.int) = x mod x
fun f (x: Int25.int) = x mod x
fun f (x: Int26.int) = x mod x
fun f (x: Int27.int) = x mod x
fun f (x: Int28.int) = x mod x
fun f (x: Int29.int) = x mod x
fun f (x: Int30.int) = x mod x
fun f (x: Int31.int) = x mod x
fun f (x: Int32.int) = x mod x
fun f (x: Int64.int) = x mod x
fun f (x: Word.word) = x mod x
fun f (x: LargeWord.word) = x mod x
fun f (x: SysWord.word) = x mod x
fun f (x: Word2.word) = x mod x
fun f (x: Word3.word) = x mod x
fun f (x: Word4.word) = x mod x
fun f (x: Word5.word) = x mod x
fun f (x: Word6.word) = x mod x
fun f (x: Word7.word) = x mod x
fun f (x: Word8.word) = x mod x
fun f (x: Word9.word) = x mod x
fun f (x: Word10.word) = x mod x
fun f (x: Word11.word) = x mod x
fun f (x: Word12.word) = x mod x
fun f (x: Word13.word) = x mod x
fun f (x: Word14.word) = x mod x
fun f (x: Word15.word) = x mod x
fun f (x: Word16.word) = x mod x
fun f (x: Word17.word) = x mod x
fun f (x: Word18.word) = x mod x
fun f (x: Word19.word) = x mod x
fun f (x: Word20.word) = x mod x
fun f (x: Word21.word) = x mod x
fun f (x: Word22.word) = x mod x
fun f (x: Word23.word) = x mod x
fun f (x: Word24.word) = x mod x
fun f (x: Word25.word) = x mod x
fun f (x: Word26.word) = x mod x
fun f (x: Word27.word) = x mod x
fun f (x: Word28.word) = x mod x
fun f (x: Word29.word) = x mod x
fun f (x: Word30.word) = x mod x
fun f (x: Word31.word) = x mod x
fun f (x: Word32.word) = x mod x
fun f (x: Word64.word) = x mod x
fun f (x: Int.int) = abs x
fun f (x: IntInf.int) = abs x
fun f (x: LargeInt.int) = abs x
fun f (x: FixedInt.int) = abs x
fun f (x: Position.int) = abs x
fun f (x: Int2.int) = abs x
fun f (x: Int3.int) = abs x
fun f (x: Int4.int) = abs x
fun f (x: Int5.int) = abs x
fun f (x: Int6.int) = abs x
fun f (x: Int7.int) = abs x
fun f (x: Int8.int) = abs x
fun f (x: Int9.int) = abs x
fun f (x: Int10.int) = abs x
fun f (x: Int11.int) = abs x
fun f (x: Int12.int) = abs x
fun f (x: Int13.int) = abs x
fun f (x: Int14.int) = abs x
fun f (x: Int15.int) = abs x
fun f (x: Int16.int) = abs x
fun f (x: Int17.int) = abs x
fun f (x: Int18.int) = abs x
fun f (x: Int19.int) = abs x
fun f (x: Int20.int) = abs x
fun f (x: Int21.int) = abs x
fun f (x: Int22.int) = abs x
fun f (x: Int23.int) = abs x
fun f (x: Int24.int) = abs x
fun f (x: Int25.int) = abs x
fun f (x: Int26.int) = abs x
fun f (x: Int27.int) = abs x
fun f (x: Int28.int) = abs x
fun f (x: Int29.int) = abs x
fun f (x: Int30.int) = abs x
fun f (x: Int31.int) = abs x
fun f (x: Int32.int) = abs x
fun f (x: Int64.int) = abs x
fun f (x: Real.real) = abs x
fun f (x: Real32.real) = abs x
fun f (x: Real64.real) = abs x
fun f (x: LargeReal.real) = abs x
fun f (x: Int.int) = x < x
fun f (x: IntInf.int) = x < x
fun f (x: LargeInt.int) = x < x
fun f (x: FixedInt.int) = x < x
fun f (x: Position.int) = x < x
fun f (x: Int2.int) = x < x
fun f (x: Int3.int) = x < x
fun f (x: Int4.int) = x < x
fun f (x: Int5.int) = x < x
fun f (x: Int6.int) = x < x
fun f (x: Int7.int) = x < x
fun f (x: Int8.int) = x < x
fun f (x: Int9.int) = x < x
fun f (x: Int10.int) = x < x
fun f (x: Int11.int) = x < x
fun f (x: Int12.int) = x < x
fun f (x: Int13.int) = x < x
fun f (x: Int14.int) = x < x
fun f (x: Int15.int) = x < x
fun f (x: Int16.int) = x < x
fun f (x: Int17.int) = x < x
fun f (x: Int18.int) = x < x
fun f (x: Int19.int) = x < x
fun f (x: Int20.int) = x < x
fun f (x: Int21.int) = x < x
fun f (x: Int22.int) = x < x
fun f (x: Int23.int) = x < x
fun f (x: Int24.int) = x < x
fun f (x: Int25.int) = x < x
fun f (x: Int26.int) = x < x
fun f (x: Int27.int) = x < x
fun f (x: Int28.int) = x < x
fun f (x: Int29.int) = x < x
fun f (x: Int30.int) = x < x
fun f (x: Int31.int) = x < x
fun f (x: Int32.int) = x < x
fun f (x: Int64.int) = x < x
fun f (x: Word.word) = x < x
fun f (x: LargeWord.word) = x < x
fun f (x: SysWord.word) = x < x
fun f (x: Word2.word) = x < x
fun f (x: Word3.word) = x < x
fun f (x: Word4.word) = x < x
fun f (x: Word5.word) = x < x
fun f (x: Word6.word) = x < x
fun f (x: Word7.word) = x < x
fun f (x: Word8.word) = x < x
fun f (x: Word9.word) = x < x
fun f (x: Word10.word) = x < x
fun f (x: Word11.word) = x < x
fun f (x: Word12.word) = x < x
fun f (x: Word13.word) = x < x
fun f (x: Word14.word) = x < x
fun f (x: Word15.word) = x < x
fun f (x: Word16.word) = x < x
fun f (x: Word17.word) = x < x
fun f (x: Word18.word) = x < x
fun f (x: Word19.word) = x < x
fun f (x: Word20.word) = x < x
fun f (x: Word21.word) = x < x
fun f (x: Word22.word) = x < x
fun f (x: Word23.word) = x < x
fun f (x: Word24.word) = x < x
fun f (x: Word25.word) = x < x
fun f (x: Word26.word) = x < x
fun f (x: Word27.word) = x < x
fun f (x: Word28.word) = x < x
fun f (x: Word29.word) = x < x
fun f (x: Word30.word) = x < x
fun f (x: Word31.word) = x < x
fun f (x: Word32.word) = x < x
fun f (x: Word64.word) = x < x
fun f (x: Real.real) = x < x
fun f (x: Real32.real) = x < x
fun f (x: Real64.real) = x < x
fun f (x: LargeReal.real) = x < x
fun f (x: Char.char) = x < x
fun f (x: String.string) = x < x
fun f (x: Int.int) = x <= x
fun f (x: IntInf.int) = x <= x
fun f (x: LargeInt.int) = x <= x
fun f (x: FixedInt.int) = x <= x
fun f (x: Position.int) = x <= x
fun f (x: Int2.int) = x <= x
fun f (x: Int3.int) = x <= x
fun f (x: Int4.int) = x <= x
fun f (x: Int5.int) = x <= x
fun f (x: Int6.int) = x <= x
fun f (x: Int7.int) = x <= x
fun f (x: Int8.int) = x <= x
fun f (x: Int9.int) = x <= x
fun f (x: Int10.int) = x <= x
fun f (x: Int11.int) = x <= x
fun f (x: Int12.int) = x <= x
fun f (x: Int13.int) = x <= x
fun f (x: Int14.int) = x <= x
fun f (x: Int15.int) = x <= x
fun f (x: Int16.int) = x <= x
fun f (x: Int17.int) = x <= x
fun f (x: Int18.int) = x <= x
fun f (x: Int19.int) = x <= x
fun f (x: Int20.int) = x <= x
fun f (x: Int21.int) = x <= x
fun f (x: Int22.int) = x <= x
fun f (x: Int23.int) = x <= x
fun f (x: Int24.int) = x <= x
fun f (x: Int25.int) = x <= x
fun f (x: Int26.int) = x <= x
fun f (x: Int27.int) = x <= x
fun f (x: Int28.int) = x <= x
fun f (x: Int29.int) = x <= x
fun f (x: Int30.int) = x <= x
fun f (x: Int31.int) = x <= x
fun f (x: Int32.int) = x <= x
fun f (x: Int64.int) = x <= x
fun f (x: Word.word) = x <= x
fun f (x: LargeWord.word) = x <= x
fun f (x: SysWord.word) = x <= x
fun f (x: Word2.word) = x <= x
fun f (x: Word3.word) = x <= x
fun f (x: Word4.word) = x <= x
fun f (x: Word5.word) = x <= x
fun f (x: Word6.word) = x <= x
fun f (x: Word7.word) = x <= x
fun f (x: Word8.word) = x <= x
fun f (x: Word9.word) = x <= x
fun f (x: Word10.word) = x <= x
fun f (x: Word11.word) = x <= x
fun f (x: Word12.word) = x <= x
fun f (x: Word13.word) = x <= x
fun f (x: Word14.word) = x <= x
fun f (x: Word15.word) = x <= x
fun f (x: Word16.word) = x <= x
fun f (x: Word17.word) = x <= x
fun f (x: Word18.word) = x <= x
fun f (x: Word19.word) = x <= x
fun f (x: Word20.word) = x <= x
fun f (x: Word21.word) = x <= x
fun f (x: Word22.word) = x <= x
fun f (x: Word23.word) = x <= x
fun f (x: Word24.word) = x <= x
fun f (x: Word25.word) = x <= x
fun f (x: Word26.word) = x <= x
fun f (x: Word27.word) = x <= x
fun f (x: Word28.word) = x <= x
fun f (x: Word29.word) = x <= x
fun f (x: Word30.word) = x <= x
fun f (x: Word31.word) = x <= x
fun f (x: Word32.word) = x <= x
fun f (x: Word64.word) = x <= x
fun f (x: Real.real) = x <= x
fun f (x: Real32.real) = x <= x
fun f (x: Real64.real) = x <= x
fun f (x: LargeReal.real) = x <= x
fun f (x: Char.char) = x <= x
fun f (x: String.string) = x <= x
fun f (x: Int.int) = x > x
fun f (x: IntInf.int) = x > x
fun f (x: LargeInt.int) = x > x
fun f (x: FixedInt.int) = x > x
fun f (x: Position.int) = x > x
fun f (x: Int2.int) = x > x
fun f (x: Int3.int) = x > x
fun f (x: Int4.int) = x > x
fun f (x: Int5.int) = x > x
fun f (x: Int6.int) = x > x
fun f (x: Int7.int) = x > x
fun f (x: Int8.int) = x > x
fun f (x: Int9.int) = x > x
fun f (x: Int10.int) = x > x
fun f (x: Int11.int) = x > x
fun f (x: Int12.int) = x > x
fun f (x: Int13.int) = x > x
fun f (x: Int14.int) = x > x
fun f (x: Int15.int) = x > x
fun f (x: Int16.int) = x > x
fun f (x: Int17.int) = x > x
fun f (x: Int18.int) = x > x
fun f (x: Int19.int) = x > x
fun f (x: Int20.int) = x > x
fun f (x: Int21.int) = x > x
fun f (x: Int22.int) = x > x
fun f (x: Int23.int) = x > x
fun f (x: Int24.int) = x > x
fun f (x: Int25.int) = x > x
fun f (x: Int26.int) = x > x
fun f (x: Int27.int) = x > x
fun f (x: Int28.int) = x > x
fun f (x: Int29.int) = x > x
fun f (x: Int30.int) = x > x
fun f (x: Int31.int) = x > x
fun f (x: Int32.int) = x > x
fun f (x: Int64.int) = x > x
fun f (x: Word.word) = x > x
fun f (x: LargeWord.word) = x > x
fun f (x: SysWord.word) = x > x
fun f (x: Word2.word) = x > x
fun f (x: Word3.word) = x > x
fun f (x: Word4.word) = x > x
fun f (x: Word5.word) = x > x
fun f (x: Word6.word) = x > x
fun f (x: Word7.word) = x > x
fun f (x: Word8.word) = x > x
fun f (x: Word9.word) = x > x
fun f (x: Word10.word) = x > x
fun f (x: Word11.word) = x > x
fun f (x: Word12.word) = x > x
fun f (x: Word13.word) = x > x
fun f (x: Word14.word) = x > x
fun f (x: Word15.word) = x > x
fun f (x: Word16.word) = x > x
fun f (x: Word17.word) = x > x
fun f (x: Word18.word) = x > x
fun f (x: Word19.word) = x > x
fun f (x: Word20.word) = x > x
fun f (x: Word21.word) = x > x
fun f (x: Word22.word) = x > x
fun f (x: Word23.word) = x > x
fun f (x: Word24.word) = x > x
fun f (x: Word25.word) = x > x
fun f (x: Word26.word) = x > x
fun f (x: Word27.word) = x > x
fun f (x: Word28.word) = x > x
fun f (x: Word29.word) = x > x
fun f (x: Word30.word) = x > x
fun f (x: Word31.word) = x > x
fun f (x: Word32.word) = x > x
fun f (x: Word64.word) = x > x
fun f (x: Real.real) = x > x
fun f (x: Real32.real) = x > x
fun f (x: Real64.real) = x > x
fun f (x: LargeReal.real) = x > x
fun f (x: Char.char) = x > x
fun f (x: String.string) = x > x
fun f (x: Int.int) = x >= x
fun f (x: IntInf.int) = x >= x
fun f (x: LargeInt.int) = x >= x
fun f (x: FixedInt.int) = x >= x
fun f (x: Position.int) = x >= x
fun f (x: Int2.int) = x >= x
fun f (x: Int3.int) = x >= x
fun f (x: Int4.int) = x >= x
fun f (x: Int5.int) = x >= x
fun f (x: Int6.int) = x >= x
fun f (x: Int7.int) = x >= x
fun f (x: Int8.int) = x >= x
fun f (x: Int9.int) = x >= x
fun f (x: Int10.int) = x >= x
fun f (x: Int11.int) = x >= x
fun f (x: Int12.int) = x >= x
fun f (x: Int13.int) = x >= x
fun f (x: Int14.int) = x >= x
fun f (x: Int15.int) = x >= x
fun f (x: Int16.int) = x >= x
fun f (x: Int17.int) = x >= x
fun f (x: Int18.int) = x >= x
fun f (x: Int19.int) = x >= x
fun f (x: Int20.int) = x >= x
fun f (x: Int21.int) = x >= x
fun f (x: Int22.int) = x >= x
fun f (x: Int23.int) = x >= x
fun f (x: Int24.int) = x >= x
fun f (x: Int25.int) = x >= x
fun f (x: Int26.int) = x >= x
fun f (x: Int27.int) = x >= x
fun f (x: Int28.int) = x >= x
fun f (x: Int29.int) = x >= x
fun f (x: Int30.int) = x >= x
fun f (x: Int31.int) = x >= x
fun f (x: Int32.int) = x >= x
fun f (x: Int64.int) = x >= x
fun f (x: Word.word) = x >= x
fun f (x: LargeWord.word) = x >= x
fun f (x: SysWord.word) = x >= x
fun f (x: Word2.word) = x >= x
fun f (x: Word3.word) = x >= x
fun f (x: Word4.word) = x >= x
fun f (x: Word5.word) = x >= x
fun f (x: Word6.word) = x >= x
fun f (x: Word7.word) = x >= x
fun f (x: Word8.word) = x >= x
fun f (x: Word9.word) = x >= x
fun f (x: Word10.word) = x >= x
fun f (x: Word11.word) = x >= x
fun f (x: Word12.word) = x >= x
fun f (x: Word13.word) = x >= x
fun f (x: Word14.word) = x >= x
fun f (x: Word15.word) = x >= x
fun f (x: Word16.word) = x >= x
fun f (x: Word17.word) = x >= x
fun f (x: Word18.word) = x >= x
fun f (x: Word19.word) = x >= x
fun f (x: Word20.word) = x >= x
fun f (x: Word21.word) = x >= x
fun f (x: Word22.word) = x >= x
fun f (x: Word23.word) = x >= x
fun f (x: Word24.word) = x >= x
fun f (x: Word25.word) = x >= x
fun f (x: Word26.word) = x >= x
fun f (x: Word27.word) = x >= x
fun f (x: Word28.word) = x >= x
fun f (x: Word29.word) = x >= x
fun f (x: Word30.word) = x >= x
fun f (x: Word31.word) = x >= x
fun f (x: Word32.word) = x >= x
fun f (x: Word64.word) = x >= x
fun f (x: Real.real) = x >= x
fun f (x: Real32.real) = x >= x
fun f (x: Real64.real) = x >= x
fun f (x: LargeReal.real) = x >= x
fun f (x: Char.char) = x >= x
fun f (x: String.string) = x >= x
