fun f x = ~ x;
fun g (x: int) = f x;
fun f x = abs x;
fun g (x: int) = f x;
fun f x = x + x;
fun g (x: int) = f x;
fun f x = x - x;
fun g (x: int) = f x;
fun f x = x * x;
fun g (x: int) = f x;
fun f x = x div x;
fun g (x: int) = f x;
fun f x = x mod x;
fun g (x: int) = f x;
fun f x = x < x;
fun g (x: int) = f x;
fun f x = x <= x;
fun g (x: int) = f x;
fun f x = x > x;
fun g (x: int) = f x;
fun f x = x >= x;
fun g (x: int) = f x;
fun f x = x / x;
fun g (x: real) = f x;
