## Copyright (C) 2020 Matthew Fluet
 #
 # MLton is released under a HPND-style license.
 # See the file MLton-LICENSE for details.
 ##

PDFLATEX := pdflatex

ml-lex.pdf: ml-lex.tex
	$(PDFLATEX) ml-lex.tex
	$(PDFLATEX) ml-lex.tex
	$(PDFLATEX) ml-lex.tex

.PHONY: clean
clean:
	../../bin/clean
