(* Copyright (C) 1999-2002 Henry Cejtin, Matthew Fluet, Suresh
 *    Jagannathan, and Stephen Weeks.
 * Copyright (C) 1997-1999 NEC Research Institute.
 *
 * MLton is released under the GNU General Public License (GPL).
 * Please see the file MLton-LICENSE for license information.
 *)
(* This is here so that the code generated by Lex and Yacc will work. *)
structure Unsafe: UNSAFE =
   struct
      structure Vector =
      	 struct
	    val sub = Primitive.Vector.sub
	 end
      structure Array =
	 struct
	    val sub = Primitive.Array.sub
	    val update = Primitive.Array.update
	    val create = Array.array
	 end
      structure CharVector = UnsafeMonoVector (type elem = char)
      structure Word8Vector = UnsafeMonoVector (type elem = word8)
      structure CharArray = UnsafeMonoArray (type elem = char)
      structure Word8Array = UnsafeMonoArray (type elem = word8)
      structure Real64Array = UnsafeMonoArray (type elem = real)
   end
